export const badWordsPH = [
    'putangina',
    'gago',
    'tanga',
    'bobo',
    'pakyu',
    'tarantado',
    'ulol',
    'gagi',
    'tangina',
    'siraulo',
    'baliw',
    'abnoy',
    'engot',
    'buwisit',
    'manyakis',
    'bastos',
    'chaka',
    'pabibo',
    'malandi'
];

export const arrayofQuestions = [
    'What program does STI offer?',
    'How to enroll as a Transferee?',
    'What are the payment methods?',
    'How to apply for scholarship?',
    'how do I apply for first-year college at STI',
    'What requirements are needed for ALS passers to enter STI College?',
    "How much is the college fee at STI College?",
    "What strands for SHS do you offer?",
    "What documents do I need for Senior High School admission?",
    "Steps to reserve a slot for new students at STI College",
    "How do I pay my fees online at STI College",
    "What happens after I make an online payment at STI College",
    "I want to report a bullying.",
    "Where can I find counseling services at STI College",
    "How can I follow up on a lost item report at STI",
    "I forgot my Microsoft Teams account email or e-mail.",
    "My ID won't tap at the gate.",
    "I can't find my ID.",
    "How long will it take to replace my ID?",
    "How do I apply for a job at STI College",
];

